name: baby_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.3
  shared_preferences: ^2.5.3
  audioplayers: ^6.1.5+1
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1
  google_mobile_ads: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/audio/
    - assets/screenshots/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
